like 'up', only run 'failfast' if feature requested

diff --git a/bin/bootstrap-cf-broker b/bin/bootstrap-cf-broker
--- a/bin/bootstrap-cf-broker
+++ b/bin/bootstrap-cf-broker
@@ -5,20 +5,18 @@ set -eu
 cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
 
 failfast() {
-  [[ "${cf_broker:-}" == "1" ]] && {
-    set +eu
-    [[ -z "${CF_API}" ]] && { echo "\$CF_API is required for --cf-broker" >> $1; }
-    [[ -z "${CF_USERNAME}" ]] && { echo "\$CF_USERNAME is required for --cf-broker" >> $1; }
-    [[ -z "${CF_PASSWORD}" ]] && { echo "\$CF_PASSWORD is required for --cf-broker" >> $1; }
-    [[ -z "${CF_ORGANIZATION}" ]] && { echo "\$CF_ORGANIZATION is required for --cf-broker" >> $1; }
-    [[ -z "${CF_SPACE}" ]] && { echo "\$CF_SPACE is required for --cf-broker" >> $1; }
-    [[ -n "$(cat "$1")" ]] && { exit 1; }
+  set +eu
+  [[ -z "${CF_API}" ]] && { echo "\$CF_API is required for --cf-broker" >> $1; }
+  [[ -z "${CF_USERNAME}" ]] && { echo "\$CF_USERNAME is required for --cf-broker" >> $1; }
+  [[ -z "${CF_PASSWORD}" ]] && { echo "\$CF_PASSWORD is required for --cf-broker" >> $1; }
+  [[ -z "${CF_ORGANIZATION}" ]] && { echo "\$CF_ORGANIZATION is required for --cf-broker" >> $1; }
+  [[ -z "${CF_SPACE}" ]] && { echo "\$CF_SPACE is required for --cf-broker" >> $1; }
+  [[ -n "$(cat "$1")" ]] && { exit 1; }
 
-    echo "Testing login to Cloud Foundry ${CF_API}..."
-    cf api "${CF_API}"
-    cf auth "${CF_USERNAME}" "${CF_PASSWORD}"
-    cf target -o "${CF_ORGANIZATION}" -s "${CF_SPACE}"
-  }
+  echo "Testing login to Cloud Foundry ${CF_API}..."
+  cf api "${CF_API}"
+  cf auth "${CF_USERNAME}" "${CF_PASSWORD}"
+  cf target -o "${CF_ORGANIZATION}" -s "${CF_SPACE}"
 }
 
 up() {
