allow specific $SCF_RELEASE_FILE from S3 bucket

diff --git a/bin/bootstrap-gke b/bin/bootstrap-gke
--- a/bin/bootstrap-gke
+++ b/bin/bootstrap-gke
@@ -27,6 +27,7 @@ export knative_version=${KNATIVE_VERSION:-0.9.0}
 
 # Install latest from CI/S3 bucket by default
 export scf_release_url=${SCF_RELEASE_URL:-}
+# Also can use SCF_RELEASE_FILE=scf-3.0.0-8f7a71d1.tgz for file from bucket
 
 usage() {
     echo "Bootstrap GKE and subsystems:"
@@ -215,9 +216,11 @@ up() {
   [[ "${cfeirini:-}" == "1" ]] && {
     echo "Install Cloud Foundry/Eirini (scf) for ${CF_SYSTEM_DOMAIN}"
     [[ "${scf_release_url:-X}" == "X" ]] && {
-      latest_scf=$(aws s3 ls s3://scf-v3/ | sort -nr | head -n1)
-      echo "--> Using scf $(echo "$latest_scf" | awk '{print $4}') from $(echo "$latest_scf" | awk '{print $1}')"
-      scf_release_url="https://scf-v3.s3.amazonaws.com/$(echo "$latest_scf" | awk '{print $4}')"
+      scf_release_file=${SCF_RELEASE_FILE:-$(aws s3 ls s3://scf-v3/ | sort -nr | head -n1 | awk '{print $4}')}
+      scf_release_date=$(aws s3 ls s3://scf-v3/ | grep "$scf_release_file" | awk '{print $1}')
+      [[ "${scf_release_date:-X}" == "X" ]] && { echo "ERROR: cannot find SCF_RELEASE_FILE=${scf_release_file}"; exit 1; }
+      echo "--> Using ${scf_release_file} from ${scf_release_date}"
+      scf_release_url="https://scf-v3.s3.amazonaws.com/${scf_release_file}"
     }
     helm upgrade --install --wait --namespace ${CF_NAMESPACE} \
       scf \
